### ISSUE TITLE
Parameters used with non-used authentication methods are validated

### ISSUE THREAD

**Issue by pekkatki** [CommunityHiQ/Frends.Community.PostFile#1]
I tried to use the task first with OAuth authentication so:
Options -> Authentication OAuth -> Token -> #var.access_token

This was a no-go and Oauth was not possible, so the authentication method was changed to WindowsIntegratedSecurity.

Validation produced error "Invalid reference #var.access_token".

Might not be an issue, but merely a user-must-be-trained-not-to-leave-unused-variables-hanging-around -type of case.

**Comment by OssiGalkin** [comment]
That's a feature/issue in FRENDS. Even if parameters are hidden in UI they are included in process specification and thus validated, and that error message tells that there is problem with #var.access_toke, probably it didn't exist anymore.
